README: updated paths in the documentation - it is now possible to use the ERROR: Option --url () must be valid URL Usage: ./crawler --url=https://mydomain.tld/ [options] Version: 1.0.3.20231110
Basic settings:
---------------
--url=<url>                      Required URL. Enclose in quotes if URL contains query parameters.
--device=<val>                   Device type for User-Agent selection. Values `desktop`, `tablet`, `mobile`. Ignored with `--user-agent`. Default value is `desktop`.
--user-agent=<val>               Override User-Agent selected by --device.
--timeout=<int>                  Request timeout (in sec). Default value is `5`.
--proxy=<host:port>              HTTP proxy in `host:port` format.
--http-auth=<val>                Basic HTTP authentication in `username:password` format.

Output settings:
----------------
--output=<val>                   Output type `text` or `json`. Default value is `text`.
--extra-columns=<val>            Extra table headers for output table with option to set width and do-not-truncate (>), e.g., `DOM,X-Cache(10),Title(40>)`.
--url-column-size=<int>          URL column width. By default, it is calculated from the size of your terminal window.
--show-inline-criticals          Show criticals from the analyzer directly in the URL table.
--show-inline-warnings           Show warnings from the analyzer directly in the URL table.
--do-not-truncate-url            Avoid truncating URLs to `--url-column-size`.
--show-scheme-and-host           Show the schema://host also of the original domain URL as well. By default, only path+query is displayed for original domain.
--hide-progress-bar              Suppress progress bar in output.
--no-color                       Disable colored output.

Resource filtering:
-------------------
--disable-javascript             Disables JavaScript downloading and removes all JavaScript code from HTML, including onclick and other on* handlers.
--disable-styles                 Disables CSS file downloading and at the same time removes all style definitions by <style> tag or inline by style attributes.
--disable-fonts                  Disables font downloading and also removes all font/font-face definitions from CSS.
--disable-images                 Disables downloading of all images and replaces found images in HTML with placeholder image only.
--disable-files                  Disables downloading of any files (typically downloadable documents) to which various links point.
--remove-all-anchor-listeners    On all links on the page remove any event listeners. Useful on some types of sites with modern JS frameworks.

Advanced crawler settings:
--------------------------
--workers=<int>                  Max concurrent workers (threads). Crawler will not make more simultaneous requests to the server than this number. Default value is `3`.
--max-reqs-per-sec=<val>         Max requests/s for whole crawler. Be careful not to cause a DoS attack. Default value is `10`.
--memory-limit=<size>            Memory limit in units M (Megabytes) or G (Gigabytes). Default value is `2048M`.
--allowed-domain-for-external-files=<val> Primarily, the crawler crawls only the URL within the domain for initial URL. This allows you to enable loading of file content from another domain as well (e.g. if you want to load assets from a CDN). Can be specified multiple times. Use can use domains with wildcard '*'.
--allowed-domain-for-crawling=<val> This option will allow you to crawl all content from other listed domains - typically in the case of language mutations on other domains. Can be specified multiple times. Use can use domains with wildcard '*'.
--include-regex=<regex>          Include only URLs matching at least one PCRE regex. Can be specified multiple times.
--ignore-regex=<regex>           Ignore URLs matching any PCRE regex. Can be specified multiple times.
--analyzer-filter-regex=<regex>  Use only analyzers that match the specified regexp.
--accept-encoding=<val>          Set `Accept-Encoding` request header. Default value is `gzip, deflate, br`.
--remove-query-params            Remove URL query parameters from crawled URLs.
--add-random-query-params        Add random query parameters to each crawled URL.
--max-queue-length=<int>         Max URL queue length. It affects memory requirements. Default value is `9000`.
--max-visited-urls=<int>         Max visited URLs. It affects memory requirements. Default value is `10000`.
--max-url-length=<int>           Max URL length in chars. It affects memory requirements. Default value is `2083`.

Expert settings:
----------------
--debug                          Activate debug mode.
--debug-log-file=<file>          Log file where to save debug messages. When --debug is not set and --debug-log-file is set, logging will be active without visible output.
--debug-url-regex=<regex>        Regex for URL(s) to debug. When crawled URL is matched, parsing, URL replacing and other actions are printed to output. Can be specified multiple times.
--result-storage=<val>           Result storage type for content and headers. Values: `memory` or `file`. Use `file` for large websites. Default value is `memory`.
--result-storage-dir=<dir>       Directory for --result-storage=file. Default value is `tmp/result-storage`.
--result-storage-compression     Enable compression for results storage. Saves disk space, but uses more CPU.
--http-cache-dir=<dir>           Cache dir for HTTP responses. You can disable cache by --http-cache-dir=''. Default value is `tmp/http-client-cache`.
--http-cache-compression         Enable compression for HTTP cache storage. Saves disk space, but uses more CPU.

File export settings:
---------------------
--output-html-report=<file>      Save HTML report into that file. Set to empty '' to disable HTML report. Default value is `tmp/report.%domain%.%datetime%.html`.
--output-json-file=<file>        Save report as JSON. Set to empty '' to disable JSON report. Default value is `tmp/output.%domain%.%datetime%.json`.
--output-text-file=<file>        Save output as TXT. Set to empty '' to disable TXT report. Default value is `tmp/output.%domain%.%datetime%.txt`.
--add-host-to-output-file        Append initial URL host to filename except sitemaps.
--add-timestamp-to-output-file   Append timestamp to filename except sitemaps.

Mailer options:
---------------
--mail-to=<email>                E-mail report recipient address(es). Can be specified multiple times.
--mail-from=<email>              E-mail sender address. Default value is `siteone-website-crawler@your-hostname.com`.
--mail-from-name=<val>           E-mail sender name. Default value is `SiteOne Crawler`.
--mail-subject-template=<val>    E-mail subject template. You can use dynamic variables %domain% and %datetime%. Default value is `Crawler Report for %domain% (%date%)`.
--mail-smtp-host=<val>           SMTP host. Default value is `localhost`.
--mail-smtp-port=<int>           SMTP port. Default value is `25`.
--mail-smtp-user=<val>           SMTP user for authentication.
--mail-smtp-pass=<val>           SMTP password for authentication.

Offline exporter options:
-------------------------
--offline-export-directory=<dir> Path to directory where to save the offline version of the website.
--offline-export-store-only-url-regex=<regex> For debug - when filled it will activate debug mode and store only URLs which match one of these PCRE regexes. Can be specified multiple times.

Sitemap options:
----------------
--sitemap-xml-file=<file>        Save sitemap to XML. `.xml` added if missing.
--sitemap-txt-file=<file>        Save sitemap to TXT. `.txt` added if missing.
--sitemap-base-priority=<val>    Base priority for XML sitemap. Default value is `0.5`.
--sitemap-priority-increase=<val> Priority increase value based on slashes count in the URL. Default value is `0.1`.

Fastest URL analyzer:
---------------------
--fastest-urls-top-limit=<int>   Number of URL addresses in TOP fastest URL addresses. Default value is `20`.
--fastest-urls-max-time=<val>    The maximum response time for an URL address to be evaluated as fast. Default value is `1`.

SEO and OpenGraph analyzer:
---------------------------
--max-heading-level=<int>        Maximal analyzer heading level from 1 to 6. Default value is `3`.

Slowest URL analyzer:
---------------------
--slowest-urls-top-limit=<int>   Number of URL addresses in TOP slowest URL addresses. Default value is `20`.
--slowest-urls-min-time=<val>    The minimum response time for an URL address to be added to TOP slow selection. Default value is `0.01`.
--slowest-urls-max-time=<val>    The maximum response time for an URL address to be evaluated as very slow. Default value is `3`.

For more detailed descriptions of parameters, see README.md.

Created with ♥ by Ján Regeš (jan.reges@siteone.cz) from www.SiteOne.io (Czech Republic) [10/2023]

ERROR: Option --url () must be valid URL

/home/janreges/siteone-website-crawler binary ( on Windows)